### PR TITLE
Adjust to trigger TF builds automatically

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@goern we will need to supply `TENSORFLOW_RELEASE_API` env var pointing to deployed tensorflow-release-api.

**Comment by fridex** [comment]
recheck

**Comment by goern** [comment]
@fridex @harshad16 I think we have not deployed a tf-build-api service yet?!

**Comment by harshad16** [comment]
@goern yes, it is not deployed yet.
we can deploy tf-release-api through the ansible-playbook in the namespace, we want it to be.
Here is the link: https://github.com/thoth-station/tensorflow-release-api#how-to-use

**Pull request merged**
