### PR TITLE
make app.sh executable

### PR DESCRIPTION
**Pull request by bissenbay**
Run `package-releases` job in `test` env and there was a crash with message `/usr/libexec/s2i/run: line 40: /opt/app-root/src/app.sh: Permission denied`. This PR makes `app.sh` executable.
Related-To: https://github.com/thoth-station/package-releases-job/pull/449

### CODE REVIEW

**Review by saisankargochhayat — COMMENTED** [review]
There seems to be no changes? Is this chmod operation on the app.sh?

**Comment by bissenbay** [comment]
> There seems to be no changes? Is this chmod operation on the app.sh?

Yes @saisankargochhayat , I just made that `app.sh` executable.

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
