### PR TITLE
Enable per-index only-if-package-seen configuration

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
/hold

Requires new thoth-storages. The mypy complains should go away with new thoth-storages as well.

https://github.com/thoth-station/storages/pull/2395

**Comment by fridex** [comment]
/unhold

Update propagated, pending review.

**Comment by goern** [comment]
@KPostOffice is this ready to be merged?

**Comment by KPostOffice** [comment]
This looks good to me but `mypy` is complaining about a couple things:

```
producer.py:181: error: Argument "verify_ssl" to "Source" has incompatible type "str"; expected "bool"
producer.py:213: error: Argument "only_if_package_seen" to "create_python_package_version_entity" of "GraphDatabase" has incompatible type "Union[str, bool]"; expected "bool"
Found 2 errors in 1 file (checked 2 source files)
Aborting due to errexit on line 14. Exit code: 1 
```

**Comment by fridex** [comment]
> This looks good to me but `mypy` is complaining about a couple things:
> 
> ```
> producer.py:181: error: Argument "verify_ssl" to "Source" has incompatible type "str"; expected "bool"
> producer.py:213: error: Argument "only_if_package_seen" to "create_python_package_version_entity" of "GraphDatabase" has incompatible type "Union[str, bool]"; expected "bool"
> Found 2 errors in 1 file (checked 2 source files)
> Aborting due to errexit on line 14. Exit code: 1 
> ```

Thanks for the review. This was caused by wrong method signature, fixed in https://github.com/thoth-station/storages/commit/983adb0dee43a67a0fa2eed2da68a96ec272d8e5. A propagated update should fix this.

**Pull request merged**
